<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RealEstate.Loader</RootNamespace>
    <AssemblyName>RealEstate.Loader</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\database\etl\cleaned\NY-House-Dataset.cleaned.csv" Link="Data\NY-House-Dataset.cleaned.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
